#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertsLoginPage
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TravelExperts")]
	public partial class AgentsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAgent(Agent instance);
    partial void UpdateAgent(Agent instance);
    partial void DeleteAgent(Agent instance);
    #endregion
		
		public AgentsDataContext() : 
				base(global::TravelExpertsLoginPage.Properties.Settings.Default.TravelExpertsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AgentsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AgentsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Agent> Agents
		{
			get
			{
				return this.GetTable<Agent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agents")]
	public partial class Agent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AgentId;
		
		private string _AgtFirstName;
		
		private string _AgtMiddleInitial;
		
		private string _AgtLastName;
		
		private string _AgtBusPhone;
		
		private string _AgtEmail;
		
		private string _AgtPosition;
		
		private System.Nullable<int> _AgencyId;
		
		private string _Password;
		
		private string _Username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgentIdChanging(int value);
    partial void OnAgentIdChanged();
    partial void OnAgtFirstNameChanging(string value);
    partial void OnAgtFirstNameChanged();
    partial void OnAgtMiddleInitialChanging(string value);
    partial void OnAgtMiddleInitialChanged();
    partial void OnAgtLastNameChanging(string value);
    partial void OnAgtLastNameChanged();
    partial void OnAgtBusPhoneChanging(string value);
    partial void OnAgtBusPhoneChanged();
    partial void OnAgtEmailChanging(string value);
    partial void OnAgtEmailChanged();
    partial void OnAgtPositionChanging(string value);
    partial void OnAgtPositionChanged();
    partial void OnAgencyIdChanging(System.Nullable<int> value);
    partial void OnAgencyIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public Agent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AgentId
		{
			get
			{
				return this._AgentId;
			}
			set
			{
				if ((this._AgentId != value))
				{
					this.OnAgentIdChanging(value);
					this.SendPropertyChanging();
					this._AgentId = value;
					this.SendPropertyChanged("AgentId");
					this.OnAgentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtFirstName", DbType="NVarChar(20)")]
		public string AgtFirstName
		{
			get
			{
				return this._AgtFirstName;
			}
			set
			{
				if ((this._AgtFirstName != value))
				{
					this.OnAgtFirstNameChanging(value);
					this.SendPropertyChanging();
					this._AgtFirstName = value;
					this.SendPropertyChanged("AgtFirstName");
					this.OnAgtFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtMiddleInitial", DbType="NVarChar(5)")]
		public string AgtMiddleInitial
		{
			get
			{
				return this._AgtMiddleInitial;
			}
			set
			{
				if ((this._AgtMiddleInitial != value))
				{
					this.OnAgtMiddleInitialChanging(value);
					this.SendPropertyChanging();
					this._AgtMiddleInitial = value;
					this.SendPropertyChanged("AgtMiddleInitial");
					this.OnAgtMiddleInitialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtLastName", DbType="NVarChar(20)")]
		public string AgtLastName
		{
			get
			{
				return this._AgtLastName;
			}
			set
			{
				if ((this._AgtLastName != value))
				{
					this.OnAgtLastNameChanging(value);
					this.SendPropertyChanging();
					this._AgtLastName = value;
					this.SendPropertyChanged("AgtLastName");
					this.OnAgtLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtBusPhone", DbType="NVarChar(20)")]
		public string AgtBusPhone
		{
			get
			{
				return this._AgtBusPhone;
			}
			set
			{
				if ((this._AgtBusPhone != value))
				{
					this.OnAgtBusPhoneChanging(value);
					this.SendPropertyChanging();
					this._AgtBusPhone = value;
					this.SendPropertyChanged("AgtBusPhone");
					this.OnAgtBusPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtEmail", DbType="NVarChar(50)")]
		public string AgtEmail
		{
			get
			{
				return this._AgtEmail;
			}
			set
			{
				if ((this._AgtEmail != value))
				{
					this.OnAgtEmailChanging(value);
					this.SendPropertyChanging();
					this._AgtEmail = value;
					this.SendPropertyChanged("AgtEmail");
					this.OnAgtEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtPosition", DbType="NVarChar(20)")]
		public string AgtPosition
		{
			get
			{
				return this._AgtPosition;
			}
			set
			{
				if ((this._AgtPosition != value))
				{
					this.OnAgtPositionChanging(value);
					this.SendPropertyChanging();
					this._AgtPosition = value;
					this.SendPropertyChanged("AgtPosition");
					this.OnAgtPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgencyId", DbType="Int")]
		public System.Nullable<int> AgencyId
		{
			get
			{
				return this._AgencyId;
			}
			set
			{
				if ((this._AgencyId != value))
				{
					this.OnAgencyIdChanging(value);
					this.SendPropertyChanging();
					this._AgencyId = value;
					this.SendPropertyChanged("AgencyId");
					this.OnAgencyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
