#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPP248VB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TravelExperts")]
	public partial class PackageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAgent(Agent instance);
    partial void UpdateAgent(Agent instance);
    partial void DeleteAgent(Agent instance);
    partial void InsertBookingDetail(BookingDetail instance);
    partial void UpdateBookingDetail(BookingDetail instance);
    partial void DeleteBookingDetail(BookingDetail instance);
    partial void InsertPackage(Package instance);
    partial void UpdatePackage(Package instance);
    partial void DeletePackage(Package instance);
    partial void InsertPackages_Products_Supplier(Packages_Products_Supplier instance);
    partial void UpdatePackages_Products_Supplier(Packages_Products_Supplier instance);
    partial void DeletePackages_Products_Supplier(Packages_Products_Supplier instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertProducts_Supplier(Products_Supplier instance);
    partial void UpdateProducts_Supplier(Products_Supplier instance);
    partial void DeleteProducts_Supplier(Products_Supplier instance);
    partial void InsertSupplier(Supplier instance);
    partial void UpdateSupplier(Supplier instance);
    partial void DeleteSupplier(Supplier instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertBooking(Booking instance);
    partial void UpdateBooking(Booking instance);
    partial void DeleteBooking(Booking instance);
    #endregion
		
		public PackageDataContext() : 
				base(global::CMPP248VB.Properties.Settings.Default.TravelExpertsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PackageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Agent> Agents
		{
			get
			{
				return this.GetTable<Agent>();
			}
		}
		
		public System.Data.Linq.Table<BookingDetail> BookingDetails
		{
			get
			{
				return this.GetTable<BookingDetail>();
			}
		}
		
		public System.Data.Linq.Table<Package> Packages
		{
			get
			{
				return this.GetTable<Package>();
			}
		}
		
		public System.Data.Linq.Table<Packages_Products_Supplier> Packages_Products_Suppliers
		{
			get
			{
				return this.GetTable<Packages_Products_Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Products_Supplier> Products_Suppliers
		{
			get
			{
				return this.GetTable<Products_Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Supplier> Suppliers
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Booking> Bookings
		{
			get
			{
				return this.GetTable<Booking>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agents")]
	public partial class Agent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AgentId;
		
		private string _AgtFirstName;
		
		private string _AgtMiddleInitial;
		
		private string _AgtLastName;
		
		private string _AgtBusPhone;
		
		private string _AgtEmail;
		
		private string _AgtPosition;
		
		private System.Nullable<int> _AgencyId;
		
		private string _Password;
		
		private string _Username;
		
		private EntitySet<Customer> _Customers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgentIdChanging(int value);
    partial void OnAgentIdChanged();
    partial void OnAgtFirstNameChanging(string value);
    partial void OnAgtFirstNameChanged();
    partial void OnAgtMiddleInitialChanging(string value);
    partial void OnAgtMiddleInitialChanged();
    partial void OnAgtLastNameChanging(string value);
    partial void OnAgtLastNameChanged();
    partial void OnAgtBusPhoneChanging(string value);
    partial void OnAgtBusPhoneChanged();
    partial void OnAgtEmailChanging(string value);
    partial void OnAgtEmailChanged();
    partial void OnAgtPositionChanging(string value);
    partial void OnAgtPositionChanged();
    partial void OnAgencyIdChanging(System.Nullable<int> value);
    partial void OnAgencyIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public Agent()
		{
			this._Customers = new EntitySet<Customer>(new Action<Customer>(this.attach_Customers), new Action<Customer>(this.detach_Customers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AgentId
		{
			get
			{
				return this._AgentId;
			}
			set
			{
				if ((this._AgentId != value))
				{
					this.OnAgentIdChanging(value);
					this.SendPropertyChanging();
					this._AgentId = value;
					this.SendPropertyChanged("AgentId");
					this.OnAgentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtFirstName", DbType="NVarChar(20)")]
		public string AgtFirstName
		{
			get
			{
				return this._AgtFirstName;
			}
			set
			{
				if ((this._AgtFirstName != value))
				{
					this.OnAgtFirstNameChanging(value);
					this.SendPropertyChanging();
					this._AgtFirstName = value;
					this.SendPropertyChanged("AgtFirstName");
					this.OnAgtFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtMiddleInitial", DbType="NVarChar(5)")]
		public string AgtMiddleInitial
		{
			get
			{
				return this._AgtMiddleInitial;
			}
			set
			{
				if ((this._AgtMiddleInitial != value))
				{
					this.OnAgtMiddleInitialChanging(value);
					this.SendPropertyChanging();
					this._AgtMiddleInitial = value;
					this.SendPropertyChanged("AgtMiddleInitial");
					this.OnAgtMiddleInitialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtLastName", DbType="NVarChar(20)")]
		public string AgtLastName
		{
			get
			{
				return this._AgtLastName;
			}
			set
			{
				if ((this._AgtLastName != value))
				{
					this.OnAgtLastNameChanging(value);
					this.SendPropertyChanging();
					this._AgtLastName = value;
					this.SendPropertyChanged("AgtLastName");
					this.OnAgtLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtBusPhone", DbType="NVarChar(20)")]
		public string AgtBusPhone
		{
			get
			{
				return this._AgtBusPhone;
			}
			set
			{
				if ((this._AgtBusPhone != value))
				{
					this.OnAgtBusPhoneChanging(value);
					this.SendPropertyChanging();
					this._AgtBusPhone = value;
					this.SendPropertyChanged("AgtBusPhone");
					this.OnAgtBusPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtEmail", DbType="NVarChar(50)")]
		public string AgtEmail
		{
			get
			{
				return this._AgtEmail;
			}
			set
			{
				if ((this._AgtEmail != value))
				{
					this.OnAgtEmailChanging(value);
					this.SendPropertyChanging();
					this._AgtEmail = value;
					this.SendPropertyChanged("AgtEmail");
					this.OnAgtEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgtPosition", DbType="NVarChar(20)")]
		public string AgtPosition
		{
			get
			{
				return this._AgtPosition;
			}
			set
			{
				if ((this._AgtPosition != value))
				{
					this.OnAgtPositionChanging(value);
					this.SendPropertyChanging();
					this._AgtPosition = value;
					this.SendPropertyChanged("AgtPosition");
					this.OnAgtPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgencyId", DbType="Int")]
		public System.Nullable<int> AgencyId
		{
			get
			{
				return this._AgencyId;
			}
			set
			{
				if ((this._AgencyId != value))
				{
					this.OnAgencyIdChanging(value);
					this.SendPropertyChanging();
					this._AgencyId = value;
					this.SendPropertyChanged("AgencyId");
					this.OnAgencyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agent_Customer", Storage="_Customers", ThisKey="AgentId", OtherKey="AgentId")]
		public EntitySet<Customer> Customers
		{
			get
			{
				return this._Customers;
			}
			set
			{
				this._Customers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Customers(Customer entity)
		{
			this.SendPropertyChanging();
			entity.Agent = this;
		}
		
		private void detach_Customers(Customer entity)
		{
			this.SendPropertyChanging();
			entity.Agent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookingDetails")]
	public partial class BookingDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BookingDetailId;
		
		private System.Nullable<double> _ItineraryNo;
		
		private System.Nullable<System.DateTime> _TripStart;
		
		private System.Nullable<System.DateTime> _TripEnd;
		
		private string _Description;
		
		private string _Destination;
		
		private System.Nullable<decimal> _BasePrice;
		
		private System.Nullable<decimal> _AgencyCommission;
		
		private System.Nullable<int> _BookingId;
		
		private string _RegionId;
		
		private string _ClassId;
		
		private string _FeeId;
		
		private System.Nullable<int> _ProductSupplierId;
		
		private EntityRef<Products_Supplier> _Products_Supplier;
		
		private EntityRef<Booking> _Booking;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookingDetailIdChanging(int value);
    partial void OnBookingDetailIdChanged();
    partial void OnItineraryNoChanging(System.Nullable<double> value);
    partial void OnItineraryNoChanged();
    partial void OnTripStartChanging(System.Nullable<System.DateTime> value);
    partial void OnTripStartChanged();
    partial void OnTripEndChanging(System.Nullable<System.DateTime> value);
    partial void OnTripEndChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnBasePriceChanging(System.Nullable<decimal> value);
    partial void OnBasePriceChanged();
    partial void OnAgencyCommissionChanging(System.Nullable<decimal> value);
    partial void OnAgencyCommissionChanged();
    partial void OnBookingIdChanging(System.Nullable<int> value);
    partial void OnBookingIdChanged();
    partial void OnRegionIdChanging(string value);
    partial void OnRegionIdChanged();
    partial void OnClassIdChanging(string value);
    partial void OnClassIdChanged();
    partial void OnFeeIdChanging(string value);
    partial void OnFeeIdChanged();
    partial void OnProductSupplierIdChanging(System.Nullable<int> value);
    partial void OnProductSupplierIdChanged();
    #endregion
		
		public BookingDetail()
		{
			this._Products_Supplier = default(EntityRef<Products_Supplier>);
			this._Booking = default(EntityRef<Booking>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BookingDetailId
		{
			get
			{
				return this._BookingDetailId;
			}
			set
			{
				if ((this._BookingDetailId != value))
				{
					this.OnBookingDetailIdChanging(value);
					this.SendPropertyChanging();
					this._BookingDetailId = value;
					this.SendPropertyChanged("BookingDetailId");
					this.OnBookingDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItineraryNo", DbType="Float")]
		public System.Nullable<double> ItineraryNo
		{
			get
			{
				return this._ItineraryNo;
			}
			set
			{
				if ((this._ItineraryNo != value))
				{
					this.OnItineraryNoChanging(value);
					this.SendPropertyChanging();
					this._ItineraryNo = value;
					this.SendPropertyChanged("ItineraryNo");
					this.OnItineraryNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> TripStart
		{
			get
			{
				return this._TripStart;
			}
			set
			{
				if ((this._TripStart != value))
				{
					this.OnTripStartChanging(value);
					this.SendPropertyChanging();
					this._TripStart = value;
					this.SendPropertyChanged("TripStart");
					this.OnTripStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> TripEnd
		{
			get
			{
				return this._TripEnd;
			}
			set
			{
				if ((this._TripEnd != value))
				{
					this.OnTripEndChanging(value);
					this.SendPropertyChanging();
					this._TripEnd = value;
					this.SendPropertyChanged("TripEnd");
					this.OnTripEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(255)")]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this.OnDestinationChanging(value);
					this.SendPropertyChanging();
					this._Destination = value;
					this.SendPropertyChanged("Destination");
					this.OnDestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasePrice", DbType="Money")]
		public System.Nullable<decimal> BasePrice
		{
			get
			{
				return this._BasePrice;
			}
			set
			{
				if ((this._BasePrice != value))
				{
					this.OnBasePriceChanging(value);
					this.SendPropertyChanging();
					this._BasePrice = value;
					this.SendPropertyChanged("BasePrice");
					this.OnBasePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgencyCommission", DbType="Money")]
		public System.Nullable<decimal> AgencyCommission
		{
			get
			{
				return this._AgencyCommission;
			}
			set
			{
				if ((this._AgencyCommission != value))
				{
					this.OnAgencyCommissionChanging(value);
					this.SendPropertyChanging();
					this._AgencyCommission = value;
					this.SendPropertyChanged("AgencyCommission");
					this.OnAgencyCommissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", DbType="Int")]
		public System.Nullable<int> BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					if (this._Booking.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionId", DbType="NVarChar(5)")]
		public string RegionId
		{
			get
			{
				return this._RegionId;
			}
			set
			{
				if ((this._RegionId != value))
				{
					this.OnRegionIdChanging(value);
					this.SendPropertyChanging();
					this._RegionId = value;
					this.SendPropertyChanged("RegionId");
					this.OnRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassId", DbType="NVarChar(5)")]
		public string ClassId
		{
			get
			{
				return this._ClassId;
			}
			set
			{
				if ((this._ClassId != value))
				{
					this.OnClassIdChanging(value);
					this.SendPropertyChanging();
					this._ClassId = value;
					this.SendPropertyChanged("ClassId");
					this.OnClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeId", DbType="NVarChar(10)")]
		public string FeeId
		{
			get
			{
				return this._FeeId;
			}
			set
			{
				if ((this._FeeId != value))
				{
					this.OnFeeIdChanging(value);
					this.SendPropertyChanging();
					this._FeeId = value;
					this.SendPropertyChanged("FeeId");
					this.OnFeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSupplierId", DbType="Int")]
		public System.Nullable<int> ProductSupplierId
		{
			get
			{
				return this._ProductSupplierId;
			}
			set
			{
				if ((this._ProductSupplierId != value))
				{
					if (this._Products_Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._ProductSupplierId = value;
					this.SendPropertyChanged("ProductSupplierId");
					this.OnProductSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Supplier_BookingDetail", Storage="_Products_Supplier", ThisKey="ProductSupplierId", OtherKey="ProductSupplierId", IsForeignKey=true)]
		public Products_Supplier Products_Supplier
		{
			get
			{
				return this._Products_Supplier.Entity;
			}
			set
			{
				Products_Supplier previousValue = this._Products_Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Products_Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Products_Supplier.Entity = null;
						previousValue.BookingDetails.Remove(this);
					}
					this._Products_Supplier.Entity = value;
					if ((value != null))
					{
						value.BookingDetails.Add(this);
						this._ProductSupplierId = value.ProductSupplierId;
					}
					else
					{
						this._ProductSupplierId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Products_Supplier");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Booking_BookingDetail", Storage="_Booking", ThisKey="BookingId", OtherKey="BookingId", IsForeignKey=true)]
		public Booking Booking
		{
			get
			{
				return this._Booking.Entity;
			}
			set
			{
				Booking previousValue = this._Booking.Entity;
				if (((previousValue != value) 
							|| (this._Booking.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Booking.Entity = null;
						previousValue.BookingDetails.Remove(this);
					}
					this._Booking.Entity = value;
					if ((value != null))
					{
						value.BookingDetails.Add(this);
						this._BookingId = value.BookingId;
					}
					else
					{
						this._BookingId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Booking");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Packages")]
	public partial class Package : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PackageId;
		
		private string _PkgName;
		
		private System.Nullable<System.DateTime> _PkgStartDate;
		
		private System.Nullable<System.DateTime> _PkgEndDate;
		
		private string _PkgDesc;
		
		private decimal _PkgBasePrice;
		
		private System.Nullable<decimal> _PkgAgencyCommission;
		
		private string _ImageFile;
		
		private EntitySet<Packages_Products_Supplier> _Packages_Products_Suppliers;
		
		private EntitySet<Booking> _Bookings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPackageIdChanging(int value);
    partial void OnPackageIdChanged();
    partial void OnPkgNameChanging(string value);
    partial void OnPkgNameChanged();
    partial void OnPkgStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPkgStartDateChanged();
    partial void OnPkgEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPkgEndDateChanged();
    partial void OnPkgDescChanging(string value);
    partial void OnPkgDescChanged();
    partial void OnPkgBasePriceChanging(decimal value);
    partial void OnPkgBasePriceChanged();
    partial void OnPkgAgencyCommissionChanging(System.Nullable<decimal> value);
    partial void OnPkgAgencyCommissionChanged();
    partial void OnImageFileChanging(string value);
    partial void OnImageFileChanged();
    #endregion
		
		public Package()
		{
			this._Packages_Products_Suppliers = new EntitySet<Packages_Products_Supplier>(new Action<Packages_Products_Supplier>(this.attach_Packages_Products_Suppliers), new Action<Packages_Products_Supplier>(this.detach_Packages_Products_Suppliers));
			this._Bookings = new EntitySet<Booking>(new Action<Booking>(this.attach_Bookings), new Action<Booking>(this.detach_Bookings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PackageId
		{
			get
			{
				return this._PackageId;
			}
			set
			{
				if ((this._PackageId != value))
				{
					this.OnPackageIdChanging(value);
					this.SendPropertyChanging();
					this._PackageId = value;
					this.SendPropertyChanged("PackageId");
					this.OnPackageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PkgName
		{
			get
			{
				return this._PkgName;
			}
			set
			{
				if ((this._PkgName != value))
				{
					this.OnPkgNameChanging(value);
					this.SendPropertyChanging();
					this._PkgName = value;
					this.SendPropertyChanged("PkgName");
					this.OnPkgNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PkgStartDate
		{
			get
			{
				return this._PkgStartDate;
			}
			set
			{
				if ((this._PkgStartDate != value))
				{
					this.OnPkgStartDateChanging(value);
					this.SendPropertyChanging();
					this._PkgStartDate = value;
					this.SendPropertyChanged("PkgStartDate");
					this.OnPkgStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PkgEndDate
		{
			get
			{
				return this._PkgEndDate;
			}
			set
			{
				if ((this._PkgEndDate != value))
				{
					this.OnPkgEndDateChanging(value);
					this.SendPropertyChanging();
					this._PkgEndDate = value;
					this.SendPropertyChanged("PkgEndDate");
					this.OnPkgEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgDesc", DbType="NVarChar(50)")]
		public string PkgDesc
		{
			get
			{
				return this._PkgDesc;
			}
			set
			{
				if ((this._PkgDesc != value))
				{
					this.OnPkgDescChanging(value);
					this.SendPropertyChanging();
					this._PkgDesc = value;
					this.SendPropertyChanged("PkgDesc");
					this.OnPkgDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgBasePrice", DbType="Money NOT NULL")]
		public decimal PkgBasePrice
		{
			get
			{
				return this._PkgBasePrice;
			}
			set
			{
				if ((this._PkgBasePrice != value))
				{
					this.OnPkgBasePriceChanging(value);
					this.SendPropertyChanging();
					this._PkgBasePrice = value;
					this.SendPropertyChanged("PkgBasePrice");
					this.OnPkgBasePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PkgAgencyCommission", DbType="Money")]
		public System.Nullable<decimal> PkgAgencyCommission
		{
			get
			{
				return this._PkgAgencyCommission;
			}
			set
			{
				if ((this._PkgAgencyCommission != value))
				{
					this.OnPkgAgencyCommissionChanging(value);
					this.SendPropertyChanging();
					this._PkgAgencyCommission = value;
					this.SendPropertyChanged("PkgAgencyCommission");
					this.OnPkgAgencyCommissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile", DbType="VarChar(50)")]
		public string ImageFile
		{
			get
			{
				return this._ImageFile;
			}
			set
			{
				if ((this._ImageFile != value))
				{
					this.OnImageFileChanging(value);
					this.SendPropertyChanging();
					this._ImageFile = value;
					this.SendPropertyChanged("ImageFile");
					this.OnImageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Package_Packages_Products_Supplier", Storage="_Packages_Products_Suppliers", ThisKey="PackageId", OtherKey="PackageId")]
		public EntitySet<Packages_Products_Supplier> Packages_Products_Suppliers
		{
			get
			{
				return this._Packages_Products_Suppliers;
			}
			set
			{
				this._Packages_Products_Suppliers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Package_Booking", Storage="_Bookings", ThisKey="PackageId", OtherKey="PackageId")]
		public EntitySet<Booking> Bookings
		{
			get
			{
				return this._Bookings;
			}
			set
			{
				this._Bookings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Packages_Products_Suppliers(Packages_Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Package = this;
		}
		
		private void detach_Packages_Products_Suppliers(Packages_Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Package = null;
		}
		
		private void attach_Bookings(Booking entity)
		{
			this.SendPropertyChanging();
			entity.Package = this;
		}
		
		private void detach_Bookings(Booking entity)
		{
			this.SendPropertyChanging();
			entity.Package = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Packages_Products_Suppliers")]
	public partial class Packages_Products_Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PackageId;
		
		private int _ProductSupplierId;
		
		private EntityRef<Package> _Package;
		
		private EntityRef<Products_Supplier> _Products_Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPackageIdChanging(int value);
    partial void OnPackageIdChanged();
    partial void OnProductSupplierIdChanging(int value);
    partial void OnProductSupplierIdChanged();
    #endregion
		
		public Packages_Products_Supplier()
		{
			this._Package = default(EntityRef<Package>);
			this._Products_Supplier = default(EntityRef<Products_Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PackageId
		{
			get
			{
				return this._PackageId;
			}
			set
			{
				if ((this._PackageId != value))
				{
					if (this._Package.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPackageIdChanging(value);
					this.SendPropertyChanging();
					this._PackageId = value;
					this.SendPropertyChanged("PackageId");
					this.OnPackageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSupplierId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductSupplierId
		{
			get
			{
				return this._ProductSupplierId;
			}
			set
			{
				if ((this._ProductSupplierId != value))
				{
					if (this._Products_Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._ProductSupplierId = value;
					this.SendPropertyChanged("ProductSupplierId");
					this.OnProductSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Package_Packages_Products_Supplier", Storage="_Package", ThisKey="PackageId", OtherKey="PackageId", IsForeignKey=true)]
		public Package Package
		{
			get
			{
				return this._Package.Entity;
			}
			set
			{
				Package previousValue = this._Package.Entity;
				if (((previousValue != value) 
							|| (this._Package.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Package.Entity = null;
						previousValue.Packages_Products_Suppliers.Remove(this);
					}
					this._Package.Entity = value;
					if ((value != null))
					{
						value.Packages_Products_Suppliers.Add(this);
						this._PackageId = value.PackageId;
					}
					else
					{
						this._PackageId = default(int);
					}
					this.SendPropertyChanged("Package");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Supplier_Packages_Products_Supplier", Storage="_Products_Supplier", ThisKey="ProductSupplierId", OtherKey="ProductSupplierId", IsForeignKey=true)]
		public Products_Supplier Products_Supplier
		{
			get
			{
				return this._Products_Supplier.Entity;
			}
			set
			{
				Products_Supplier previousValue = this._Products_Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Products_Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Products_Supplier.Entity = null;
						previousValue.Packages_Products_Suppliers.Remove(this);
					}
					this._Products_Supplier.Entity = value;
					if ((value != null))
					{
						value.Packages_Products_Suppliers.Add(this);
						this._ProductSupplierId = value.ProductSupplierId;
					}
					else
					{
						this._ProductSupplierId = default(int);
					}
					this.SendPropertyChanged("Products_Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductId;
		
		private string _ProdName;
		
		private EntitySet<Products_Supplier> _Products_Suppliers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnProdNameChanging(string value);
    partial void OnProdNameChanged();
    #endregion
		
		public Product()
		{
			this._Products_Suppliers = new EntitySet<Products_Supplier>(new Action<Products_Supplier>(this.attach_Products_Suppliers), new Action<Products_Supplier>(this.detach_Products_Suppliers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProdName
		{
			get
			{
				return this._ProdName;
			}
			set
			{
				if ((this._ProdName != value))
				{
					this.OnProdNameChanging(value);
					this.SendPropertyChanging();
					this._ProdName = value;
					this.SendPropertyChanged("ProdName");
					this.OnProdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Products_Supplier", Storage="_Products_Suppliers", ThisKey="ProductId", OtherKey="ProductId")]
		public EntitySet<Products_Supplier> Products_Suppliers
		{
			get
			{
				return this._Products_Suppliers;
			}
			set
			{
				this._Products_Suppliers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products_Suppliers(Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_Products_Suppliers(Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products_Suppliers")]
	public partial class Products_Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductSupplierId;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<int> _SupplierId;
		
		private EntitySet<BookingDetail> _BookingDetails;
		
		private EntitySet<Packages_Products_Supplier> _Packages_Products_Suppliers;
		
		private EntityRef<Product> _Product;
		
		private EntityRef<Supplier> _Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductSupplierIdChanging(int value);
    partial void OnProductSupplierIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnSupplierIdChanging(System.Nullable<int> value);
    partial void OnSupplierIdChanged();
    #endregion
		
		public Products_Supplier()
		{
			this._BookingDetails = new EntitySet<BookingDetail>(new Action<BookingDetail>(this.attach_BookingDetails), new Action<BookingDetail>(this.detach_BookingDetails));
			this._Packages_Products_Suppliers = new EntitySet<Packages_Products_Supplier>(new Action<Packages_Products_Supplier>(this.attach_Packages_Products_Suppliers), new Action<Packages_Products_Supplier>(this.detach_Packages_Products_Suppliers));
			this._Product = default(EntityRef<Product>);
			this._Supplier = default(EntityRef<Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSupplierId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductSupplierId
		{
			get
			{
				return this._ProductSupplierId;
			}
			set
			{
				if ((this._ProductSupplierId != value))
				{
					this.OnProductSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._ProductSupplierId = value;
					this.SendPropertyChanged("ProductSupplierId");
					this.OnProductSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierId", DbType="Int")]
		public System.Nullable<int> SupplierId
		{
			get
			{
				return this._SupplierId;
			}
			set
			{
				if ((this._SupplierId != value))
				{
					if (this._Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._SupplierId = value;
					this.SendPropertyChanged("SupplierId");
					this.OnSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Supplier_BookingDetail", Storage="_BookingDetails", ThisKey="ProductSupplierId", OtherKey="ProductSupplierId")]
		public EntitySet<BookingDetail> BookingDetails
		{
			get
			{
				return this._BookingDetails;
			}
			set
			{
				this._BookingDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Supplier_Packages_Products_Supplier", Storage="_Packages_Products_Suppliers", ThisKey="ProductSupplierId", OtherKey="ProductSupplierId")]
		public EntitySet<Packages_Products_Supplier> Packages_Products_Suppliers
		{
			get
			{
				return this._Packages_Products_Suppliers;
			}
			set
			{
				this._Packages_Products_Suppliers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Products_Supplier", Storage="_Product", ThisKey="ProductId", OtherKey="ProductId", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.Products_Suppliers.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.Products_Suppliers.Add(this);
						this._ProductId = value.ProductId;
					}
					else
					{
						this._ProductId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Products_Supplier", Storage="_Supplier", ThisKey="SupplierId", OtherKey="SupplierId", IsForeignKey=true)]
		public Supplier Supplier
		{
			get
			{
				return this._Supplier.Entity;
			}
			set
			{
				Supplier previousValue = this._Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Supplier.Entity = null;
						previousValue.Products_Suppliers.Remove(this);
					}
					this._Supplier.Entity = value;
					if ((value != null))
					{
						value.Products_Suppliers.Add(this);
						this._SupplierId = value.SupplierId;
					}
					else
					{
						this._SupplierId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BookingDetails(BookingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Products_Supplier = this;
		}
		
		private void detach_BookingDetails(BookingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Products_Supplier = null;
		}
		
		private void attach_Packages_Products_Suppliers(Packages_Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Products_Supplier = this;
		}
		
		private void detach_Packages_Products_Suppliers(Packages_Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Products_Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Suppliers")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SupplierId;
		
		private string _SupName;
		
		private EntitySet<Products_Supplier> _Products_Suppliers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSupplierIdChanging(int value);
    partial void OnSupplierIdChanged();
    partial void OnSupNameChanging(string value);
    partial void OnSupNameChanged();
    #endregion
		
		public Supplier()
		{
			this._Products_Suppliers = new EntitySet<Products_Supplier>(new Action<Products_Supplier>(this.attach_Products_Suppliers), new Action<Products_Supplier>(this.detach_Products_Suppliers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SupplierId
		{
			get
			{
				return this._SupplierId;
			}
			set
			{
				if ((this._SupplierId != value))
				{
					this.OnSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._SupplierId = value;
					this.SendPropertyChanged("SupplierId");
					this.OnSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupName", DbType="NVarChar(255)")]
		public string SupName
		{
			get
			{
				return this._SupName;
			}
			set
			{
				if ((this._SupName != value))
				{
					this.OnSupNameChanging(value);
					this.SendPropertyChanging();
					this._SupName = value;
					this.SendPropertyChanged("SupName");
					this.OnSupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Products_Supplier", Storage="_Products_Suppliers", ThisKey="SupplierId", OtherKey="SupplierId")]
		public EntitySet<Products_Supplier> Products_Suppliers
		{
			get
			{
				return this._Products_Suppliers;
			}
			set
			{
				this._Products_Suppliers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products_Suppliers(Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = this;
		}
		
		private void detach_Products_Suppliers(Products_Supplier entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerId;
		
		private string _CustFirstName;
		
		private string _CustLastName;
		
		private string _CustAddress;
		
		private string _CustCity;
		
		private string _CustProv;
		
		private string _CustPostal;
		
		private string _CustCountry;
		
		private string _CustHomePhone;
		
		private string _CustBusPhone;
		
		private string _CustEmail;
		
		private System.Nullable<int> _AgentId;
		
		private string _CustUsername;
		
		private string _CustPassword;
		
		private EntitySet<Booking> _Bookings;
		
		private EntityRef<Agent> _Agent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(int value);
    partial void OnCustomerIdChanged();
    partial void OnCustFirstNameChanging(string value);
    partial void OnCustFirstNameChanged();
    partial void OnCustLastNameChanging(string value);
    partial void OnCustLastNameChanged();
    partial void OnCustAddressChanging(string value);
    partial void OnCustAddressChanged();
    partial void OnCustCityChanging(string value);
    partial void OnCustCityChanged();
    partial void OnCustProvChanging(string value);
    partial void OnCustProvChanged();
    partial void OnCustPostalChanging(string value);
    partial void OnCustPostalChanged();
    partial void OnCustCountryChanging(string value);
    partial void OnCustCountryChanged();
    partial void OnCustHomePhoneChanging(string value);
    partial void OnCustHomePhoneChanged();
    partial void OnCustBusPhoneChanging(string value);
    partial void OnCustBusPhoneChanged();
    partial void OnCustEmailChanging(string value);
    partial void OnCustEmailChanged();
    partial void OnAgentIdChanging(System.Nullable<int> value);
    partial void OnAgentIdChanged();
    partial void OnCustUsernameChanging(string value);
    partial void OnCustUsernameChanged();
    partial void OnCustPasswordChanging(string value);
    partial void OnCustPasswordChanged();
    #endregion
		
		public Customer()
		{
			this._Bookings = new EntitySet<Booking>(new Action<Booking>(this.attach_Bookings), new Action<Booking>(this.detach_Bookings));
			this._Agent = default(EntityRef<Agent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustFirstName", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string CustFirstName
		{
			get
			{
				return this._CustFirstName;
			}
			set
			{
				if ((this._CustFirstName != value))
				{
					this.OnCustFirstNameChanging(value);
					this.SendPropertyChanging();
					this._CustFirstName = value;
					this.SendPropertyChanged("CustFirstName");
					this.OnCustFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustLastName", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string CustLastName
		{
			get
			{
				return this._CustLastName;
			}
			set
			{
				if ((this._CustLastName != value))
				{
					this.OnCustLastNameChanging(value);
					this.SendPropertyChanging();
					this._CustLastName = value;
					this.SendPropertyChanged("CustLastName");
					this.OnCustLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustAddress", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string CustAddress
		{
			get
			{
				return this._CustAddress;
			}
			set
			{
				if ((this._CustAddress != value))
				{
					this.OnCustAddressChanging(value);
					this.SendPropertyChanging();
					this._CustAddress = value;
					this.SendPropertyChanged("CustAddress");
					this.OnCustAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CustCity
		{
			get
			{
				return this._CustCity;
			}
			set
			{
				if ((this._CustCity != value))
				{
					this.OnCustCityChanging(value);
					this.SendPropertyChanging();
					this._CustCity = value;
					this.SendPropertyChanged("CustCity");
					this.OnCustCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustProv", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string CustProv
		{
			get
			{
				return this._CustProv;
			}
			set
			{
				if ((this._CustProv != value))
				{
					this.OnCustProvChanging(value);
					this.SendPropertyChanging();
					this._CustProv = value;
					this.SendPropertyChanged("CustProv");
					this.OnCustProvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustPostal", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string CustPostal
		{
			get
			{
				return this._CustPostal;
			}
			set
			{
				if ((this._CustPostal != value))
				{
					this.OnCustPostalChanging(value);
					this.SendPropertyChanging();
					this._CustPostal = value;
					this.SendPropertyChanged("CustPostal");
					this.OnCustPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCountry", DbType="NVarChar(25)")]
		public string CustCountry
		{
			get
			{
				return this._CustCountry;
			}
			set
			{
				if ((this._CustCountry != value))
				{
					this.OnCustCountryChanging(value);
					this.SendPropertyChanging();
					this._CustCountry = value;
					this.SendPropertyChanged("CustCountry");
					this.OnCustCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustHomePhone", DbType="NVarChar(20)")]
		public string CustHomePhone
		{
			get
			{
				return this._CustHomePhone;
			}
			set
			{
				if ((this._CustHomePhone != value))
				{
					this.OnCustHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._CustHomePhone = value;
					this.SendPropertyChanged("CustHomePhone");
					this.OnCustHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustBusPhone", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CustBusPhone
		{
			get
			{
				return this._CustBusPhone;
			}
			set
			{
				if ((this._CustBusPhone != value))
				{
					this.OnCustBusPhoneChanging(value);
					this.SendPropertyChanging();
					this._CustBusPhone = value;
					this.SendPropertyChanged("CustBusPhone");
					this.OnCustBusPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CustEmail
		{
			get
			{
				return this._CustEmail;
			}
			set
			{
				if ((this._CustEmail != value))
				{
					this.OnCustEmailChanging(value);
					this.SendPropertyChanging();
					this._CustEmail = value;
					this.SendPropertyChanged("CustEmail");
					this.OnCustEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentId", DbType="Int")]
		public System.Nullable<int> AgentId
		{
			get
			{
				return this._AgentId;
			}
			set
			{
				if ((this._AgentId != value))
				{
					if (this._Agent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAgentIdChanging(value);
					this.SendPropertyChanging();
					this._AgentId = value;
					this.SendPropertyChanged("AgentId");
					this.OnAgentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustUsername", DbType="VarChar(50)")]
		public string CustUsername
		{
			get
			{
				return this._CustUsername;
			}
			set
			{
				if ((this._CustUsername != value))
				{
					this.OnCustUsernameChanging(value);
					this.SendPropertyChanging();
					this._CustUsername = value;
					this.SendPropertyChanged("CustUsername");
					this.OnCustUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustPassword", DbType="VarChar(MAX)")]
		public string CustPassword
		{
			get
			{
				return this._CustPassword;
			}
			set
			{
				if ((this._CustPassword != value))
				{
					this.OnCustPasswordChanging(value);
					this.SendPropertyChanging();
					this._CustPassword = value;
					this.SendPropertyChanged("CustPassword");
					this.OnCustPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Booking", Storage="_Bookings", ThisKey="CustomerId", OtherKey="CustomerId")]
		public EntitySet<Booking> Bookings
		{
			get
			{
				return this._Bookings;
			}
			set
			{
				this._Bookings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Agent_Customer", Storage="_Agent", ThisKey="AgentId", OtherKey="AgentId", IsForeignKey=true)]
		public Agent Agent
		{
			get
			{
				return this._Agent.Entity;
			}
			set
			{
				Agent previousValue = this._Agent.Entity;
				if (((previousValue != value) 
							|| (this._Agent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Agent.Entity = null;
						previousValue.Customers.Remove(this);
					}
					this._Agent.Entity = value;
					if ((value != null))
					{
						value.Customers.Add(this);
						this._AgentId = value.AgentId;
					}
					else
					{
						this._AgentId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Agent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bookings(Booking entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_Bookings(Booking entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bookings")]
	public partial class Booking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BookingId;
		
		private System.Nullable<System.DateTime> _BookingDate;
		
		private string _BookingNo;
		
		private System.Nullable<double> _TravelerCount;
		
		private System.Nullable<int> _CustomerId;
		
		private string _TripTypeId;
		
		private System.Nullable<int> _PackageId;
		
		private EntitySet<BookingDetail> _BookingDetails;
		
		private EntityRef<Customer> _Customer;
		
		private EntityRef<Package> _Package;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookingIdChanging(int value);
    partial void OnBookingIdChanged();
    partial void OnBookingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBookingDateChanged();
    partial void OnBookingNoChanging(string value);
    partial void OnBookingNoChanged();
    partial void OnTravelerCountChanging(System.Nullable<double> value);
    partial void OnTravelerCountChanged();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnTripTypeIdChanging(string value);
    partial void OnTripTypeIdChanged();
    partial void OnPackageIdChanging(System.Nullable<int> value);
    partial void OnPackageIdChanged();
    #endregion
		
		public Booking()
		{
			this._BookingDetails = new EntitySet<BookingDetail>(new Action<BookingDetail>(this.attach_BookingDetails), new Action<BookingDetail>(this.detach_BookingDetails));
			this._Customer = default(EntityRef<Customer>);
			this._Package = default(EntityRef<Package>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BookingId
		{
			get
			{
				return this._BookingId;
			}
			set
			{
				if ((this._BookingId != value))
				{
					this.OnBookingIdChanging(value);
					this.SendPropertyChanging();
					this._BookingId = value;
					this.SendPropertyChanged("BookingId");
					this.OnBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BookingDate
		{
			get
			{
				return this._BookingDate;
			}
			set
			{
				if ((this._BookingDate != value))
				{
					this.OnBookingDateChanging(value);
					this.SendPropertyChanging();
					this._BookingDate = value;
					this.SendPropertyChanged("BookingDate");
					this.OnBookingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingNo", DbType="NVarChar(50)")]
		public string BookingNo
		{
			get
			{
				return this._BookingNo;
			}
			set
			{
				if ((this._BookingNo != value))
				{
					this.OnBookingNoChanging(value);
					this.SendPropertyChanging();
					this._BookingNo = value;
					this.SendPropertyChanged("BookingNo");
					this.OnBookingNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelerCount", DbType="Float")]
		public System.Nullable<double> TravelerCount
		{
			get
			{
				return this._TravelerCount;
			}
			set
			{
				if ((this._TravelerCount != value))
				{
					this.OnTravelerCountChanging(value);
					this.SendPropertyChanging();
					this._TravelerCount = value;
					this.SendPropertyChanged("TravelerCount");
					this.OnTravelerCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripTypeId", DbType="NVarChar(1)")]
		public string TripTypeId
		{
			get
			{
				return this._TripTypeId;
			}
			set
			{
				if ((this._TripTypeId != value))
				{
					this.OnTripTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TripTypeId = value;
					this.SendPropertyChanged("TripTypeId");
					this.OnTripTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageId", DbType="Int")]
		public System.Nullable<int> PackageId
		{
			get
			{
				return this._PackageId;
			}
			set
			{
				if ((this._PackageId != value))
				{
					if (this._Package.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPackageIdChanging(value);
					this.SendPropertyChanging();
					this._PackageId = value;
					this.SendPropertyChanged("PackageId");
					this.OnPackageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Booking_BookingDetail", Storage="_BookingDetails", ThisKey="BookingId", OtherKey="BookingId")]
		public EntitySet<BookingDetail> BookingDetails
		{
			get
			{
				return this._BookingDetails;
			}
			set
			{
				this._BookingDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Booking", Storage="_Customer", ThisKey="CustomerId", OtherKey="CustomerId", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.Bookings.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.Bookings.Add(this);
						this._CustomerId = value.CustomerId;
					}
					else
					{
						this._CustomerId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Package_Booking", Storage="_Package", ThisKey="PackageId", OtherKey="PackageId", IsForeignKey=true)]
		public Package Package
		{
			get
			{
				return this._Package.Entity;
			}
			set
			{
				Package previousValue = this._Package.Entity;
				if (((previousValue != value) 
							|| (this._Package.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Package.Entity = null;
						previousValue.Bookings.Remove(this);
					}
					this._Package.Entity = value;
					if ((value != null))
					{
						value.Bookings.Add(this);
						this._PackageId = value.PackageId;
					}
					else
					{
						this._PackageId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Package");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BookingDetails(BookingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Booking = this;
		}
		
		private void detach_BookingDetails(BookingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Booking = null;
		}
	}
}
#pragma warning restore 1591
