<?xml version="1.0" encoding="utf-8"?><Database Name="TravelExperts" Class="ProductSuppliersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\bachirsql;Initial Catalog=TravelExperts;Integrated Security=True" SettingsObjectName="ProductSupplier.Properties.Settings" SettingsPropertyName="TravelExpertsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products_Suppliers" Member="Products_Suppliers">
    <Type Name="Products_Supplier">
      <Column Name="ProductSupplierId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>