<?xml version="1.0" encoding="utf-8"?><Database Name="TravelExperts" Class="ProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\Bachirsql;Initial Catalog=TravelExperts;Integrated Security=True" SettingsObjectName="Products.Properties.Settings" SettingsPropertyName="TravelExpertsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProdName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>